name: weather_app
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  google_fonts: 6.1.0
  flutter_dotenv: ^5.1.0
  dio: ^5.4.3+1
  geolocator: ^11.1.0
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/noData1.png
    - assets/noData2.png
    - assets/search.png
    - .env




